### ISSUE TITLE
Support multiple Jenkins instances

### ISSUE THREAD

**Issue by tkucorporate** [tuo/jenkins-monitor#6]
Hi there, 

your script is very nice and as we have multiple jenkins instances to manage (8 pcs.) I wanted to ask if there's a possibility you can extend the script to support that??
Would be great.
Thanks, Thomas

**Comment by twksos** [comment]
@tkucorporate 
Let me confirm. You got 8 jenkins server and want to config multiple jenkins server in address in the dashboard, right?

**Comment by tkucorporate** [comment]
@twksos

Hi there, that's correct. My thought was to have an overview of the failing / unstable jobs of these servers. Its uncomfortable having to look at 8 websites in the morning to get the latest infos about the jobs.

I tried to implement this myself, but I didn't get it working. My plan was to store the server urls within an array, but when changing the iteration for every server combined with the autoRefresh and json loading, I approached my limits in java script ;)
So I wanted to ask, if there's a chance if you can give me a hint/example about that.

Thanks in advance, Thomas

**Comment by tkucorporate** [comment]
Sorry, I accidently closed the issue. Reopened it again...

**Comment by tkucorporate** [comment]
@twksos 
Is there any chance you can help me?
Thanks, Thomas

**Comment by twksos** [comment]
Hi @tkucorporate, I've updated the branch multi-jenkins: 

3f93a74ec8f02a1ccc3d3d3cad9354f2b2ac2e5c

However, I don't have a jsonp enabled jenkins server currently. I would suggest a chrome extension called `Allow-Control-Allow-Origin` for cross domain issue.

Please let me know if you got any other issue.

**Comment by tkucorporate** [comment]
@twksos:

Thank you very much - works like charm ;)
